<?php
/**
 * Copyright © 28Software (https://28software.com)
 * See LICENSE for the license details.
 */
declare(strict_types = 1);

use Magento\Framework\View\Element\Template;
use TESoftware\BuySafeGuarantee\ViewModel\Tracker;

/** @var Template $block */
/** @var Tracker $viewModel */

$viewModel = $block->getViewModel();
$orderId = $block->getOrderId();

?>
<!-- BEGIN: buySAFE Seal -->
<script type="text/javascript" src="<?= /** @noEscape */ $viewModel->getScriptUrl() ?>"></script>
<!-- END: buySAFE Seal -->
