<?php
/**
 * Copyright © 28Software (https://28software.com)
 * See LICENSE for the license details.
 */
declare(strict_types = 1);

use Magento\Framework\View\Element\Template;
use TESoftware\BuySafeGuarantee\ViewModel\Tracker;

/** @var Template $block */
/** @var Tracker $viewModel */

$viewModel = $block->getViewModel();
$orderId = $block->getOrderId();

?>
<!-- Shopping Guarantee Seal -->
<script type="text/javascript" src="<?= /** @noEscape */ $viewModel->getScriptUrl() ?>"></script>
<?php if ($viewModel->isPdpImageHidden()): ?>
<style>
    span[id='Kicker Custom Minimal2_1'], span[id='Kicker Custom Minimal2_2'] {
        display: none !important;
    }
    ._GUARANTEE_Kicker_Container {
        display: none !important;
    }
</style>
<?php endif; ?>
