<?php
/**
 * Copyright © 28Software (https://28software.com)
 * See LICENSE for the license details.
 */
declare(strict_types = 1);

use Magento\Checkout\Block\Onepage\Success;
use Magento\Framework\Escaper;
use TESoftware\BuySafeGuarantee\ViewModel\Tracker;

/** @var Escaper $escaper */
/** @var Success $block */
/** @var Tracker $viewModel */

$viewModel = $block->getViewModel();
$incrementId = $block->getOrderId();
?>
<?php if ($viewModel->isShowGuaranteeAtCheckout()): ?>
<!-- Shopping Guarantee -->
<script>
    const script = document.createElement('script')
    script.src = '<?= $escaper->escapeJs($viewModel->getScriptUrl()) ?>';
    script.type = 'text/javascript';
    script.onload = 'addGuaranteeData()';
    document.head.append(script);
</script>
<script>
    function addGuaranteeData() {
        if( window._GUARANTEE && _GUARANTEE.Loaded ) {
            _GUARANTEE.Guarantee.order = "<?= /** @noEscape */ $incrementId ?>";
            _GUARANTEE.Guarantee.subtotal = "<?= /** @noEscape */ $viewModel->getOrderSubtotal($incrementId) ?>";
            _GUARANTEE.Guarantee.currency = "<?= /** @noEscape */ $viewModel->getOrderCurrencyCode($incrementId) ?>";
            _GUARANTEE.Guarantee.email = "<?= /** @noEscape */ $viewModel->getOrderCustomerEmail($incrementId) ?>";
            _GUARANTEE.WriteGuarantee();
        }
    }
</script>
<!-- /Shopping Guarantee -->
<?php endif; ?>
